"""empty message

Revision ID: 0422213a2515
Revises: 
Create Date: 2022-05-10 16:47:33.509285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0422213a2515'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('member_no', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('member_password', sa.String(length=500), nullable=False),
    sa.Column('member_email', sa.String(length=30), nullable=False),
    sa.Column('member_name', sa.String(length=20), nullable=False),
    sa.Column('member_type', sa.SmallInteger(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('member_no')
    )
    op.create_table('question',
    sa.Column('question_no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ques_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('member_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_no'], ['member.member_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_no')
    )
    op.create_table('storybook',
    sa.Column('book_no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_title', sa.String(length=50), nullable=False),
    sa.Column('book_con', sa.Text(), nullable=False),
    sa.Column('book_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('member_no', sa.Integer(), nullable=False),
    sa.Column('speak_path', sa.String(length=500), nullable=True),
    sa.Column('avg', sa.Float(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['member_no'], ['member.member_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_no')
    )
    op.create_table('cover_image',
    sa.Column('book_no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('img_path', sa.String(length=500), nullable=False),
    sa.Column('maked_img_path', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['book_no'], ['storybook.book_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_no')
    )
    op.create_table('pageimage',
    sa.Column('pageimage_no', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('book_no', sa.Integer(), nullable=True),
    sa.Column('pageper_img_no', sa.Integer(), nullable=False),
    sa.Column('pageimg_path', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['book_no'], ['storybook.book_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pageimage_no')
    )
    op.create_table('question_comment',
    sa.Column('comment_no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_no', sa.Integer(), nullable=False),
    sa.Column('question_no', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('comment_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['member_no'], ['member.member_no'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_no'], ['question.question_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_no')
    )
    op.create_table('rating',
    sa.Column('rating_no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_no', sa.Integer(), nullable=False),
    sa.Column('book_no', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_no'], ['storybook.book_no'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_no'], ['member.member_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rating_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('question_comment')
    op.drop_table('pageimage')
    op.drop_table('cover_image')
    op.drop_table('storybook')
    op.drop_table('question')
    op.drop_table('member')
    # ### end Alembic commands ###
