"""empty message

Revision ID: 3f3644ee7d8d
Revises: 
Create Date: 2022-04-15 14:47:43.177184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3644ee7d8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('member_no', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('member_password', sa.String(length=30), nullable=False),
    sa.Column('member_email', sa.String(length=30), nullable=False),
    sa.Column('member_name', sa.String(length=20), nullable=False),
    sa.Column('member_type', sa.SmallInteger(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('member_no')
    )
    op.create_table('question',
    sa.Column('question_no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ques_title', sa.String(length=50), nullable=False),
    sa.Column('ques_con', sa.String(length=1000), nullable=False),
    sa.Column('ques_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('member_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_no'], ['member.member_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_no')
    )
    op.create_table('storybook',
    sa.Column('book_no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_con', sa.Text(), nullable=False),
    sa.Column('book_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('member_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_no'], ['member.member_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_no')
    )
    op.create_table('image',
    sa.Column('img_no', sa.Integer(), nullable=False),
    sa.Column('book_no', sa.Integer(), nullable=False),
    sa.Column('img_path', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['book_no'], ['storybook.book_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('img_no', 'book_no')
    )
    op.create_table('question_comment',
    sa.Column('comment_no', sa.Integer(), nullable=False),
    sa.Column('member_no', sa.Integer(), nullable=False),
    sa.Column('question_no', sa.Integer(), nullable=False),
    sa.Column('comment_con', sa.String(length=200), nullable=False),
    sa.Column('comment_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['member_no'], ['member.member_no'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_no'], ['question.question_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_no', 'member_no', 'question_no')
    )
    op.create_table('rating',
    sa.Column('rating_no', sa.Integer(), nullable=False),
    sa.Column('member_no', sa.Integer(), nullable=False),
    sa.Column('book_no', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_no'], ['storybook.book_no'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_no'], ['member.member_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rating_no', 'member_no', 'book_no'),
    sa.UniqueConstraint('book_no'),
    sa.UniqueConstraint('member_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('question_comment')
    op.drop_table('image')
    op.drop_table('storybook')
    op.drop_table('question')
    op.drop_table('member')
    # ### end Alembic commands ###
